### ISSUE TITLE
undefined is not an object (evaluating 'a.result')

### ISSUE THREAD

**Issue by ghost** [try2codesecure/grafana_dashboards#1]
Hello,

Thank you for sharing this dashboard.

I can't get it to work and I don't know if it's me doing something wrong.
All panels show the error "undefined is not an object (evaluating 'a.result')"

I am able to see the query into the query inspector. I tried to troubleshoot my self but I am new in using Grafana.

Thanks

**Comment by try2codesecure** [comment]
Hi pozkr.
Can you query the metrics from local network?

I figured out that the default node exporter config can only be queried from localhost:
`root@OpenWrt:/etc/config# cat prometheus-node-exporter-lua`
config prometheus-node-exporter-lua 'main'
	option listen_interface 'loopback'
	option listen_ipv6 '0'
	option listen_port '9100'
`root@OpenWrt:/etc/config# netstat -tulpn | grep 9100`
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      1808/lua
`root@OpenWrt:/etc/config# ps | grep prometheus`
1808 root      1920 S    {prometheus-node} /usr/bin/lua /usr/bin/prometheus-node-exporter-lua --bind 127.0.0.1 --port 9100

If you intend it to use it from your local lan, you should change the config:
`sed -i.bak 's#loopback#lan#g' /etc/config/prometheus-node-exporter-lua`
`root@OpenWrt:/etc/config# /etc/init.d/prometheus-node-exporter-lua restart`
`root@OpenWrt:/etc/config# netstat -tulpn | grep 9100`
tcp        0      0 YOUR_ROUTER_IP:9100        0.0.0.0:*               LISTEN      3469/lua
`root@OpenWrt:/etc/config# ps | grep prometheus`
 3469 root      1920 S    {prometheus-node} /usr/bin/lua /usr/bin/prometheus-node-exporter-lua --bind YOUR_ROUTER_IP --port 9100
Then you should be able to query from your lan:
`[user@HOST-IN-LAN ~]$ nmap YOUR_ROUTER_IP -p 9100`
9100/tcp open  jetdirect
`[user@HOST-IN-LAN ~]$ curl YOUR_ROUTER_IP:9100/metrics`
or just open the browser & open http://YOUR_ROUTER_IP:9100/metrics

**Comment by try2codesecure** [comment]
You can use the step-by-step config explained here => https://www.cloudrocket.at/posts/monitor-openwrt-nodes-with-prometheus/
